package com.xcape.simplemmomod.ui.theme
import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF735C00)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFE087)
val md_theme_light_onPrimaryContainer = Color(0xFF231A00)
val md_theme_light_secondary = Color(0xFFB3272B)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFDAD7)
val md_theme_light_onSecondaryContainer = Color(0xFF410004)
val md_theme_light_tertiary = Color(0xFF0961A4)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFD2E4FF)
val md_theme_light_onTertiaryContainer = Color(0xFF001C37)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF8FDFF)
val md_theme_light_onBackground = Color(0xFF001F25)
val md_theme_light_surface = Color(0xFFF8FDFF)
val md_theme_light_onSurface = Color(0xFF001F25)
val md_theme_light_surfaceVariant = Color(0xFFEBE1CF)
val md_theme_light_onSurfaceVariant = Color(0xFF4C4639)
val md_theme_light_outline = Color(0xFF7D7667)
val md_theme_light_inverseOnSurface = Color(0xFFD6F6FF)
val md_theme_light_inverseSurface = Color(0xFF00363F)
val md_theme_light_inversePrimary = Color(0xFFE9C348)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF735C00)
val md_theme_light_outlineVariant = Color(0xFFCFC6B4)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFE9C348)
val md_theme_dark_onPrimary = Color(0xFF3C2F00)
val md_theme_dark_primaryContainer = Color(0xFF574500)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFE087)
val md_theme_dark_secondary = Color(0xFFFFB3AE)
val md_theme_dark_onSecondary = Color(0xFF68000B)
val md_theme_dark_secondaryContainer = Color(0xFF910817)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFDAD7)
val md_theme_dark_tertiary = Color(0xFFA0CAFF)
val md_theme_dark_onTertiary = Color(0xFF003259)
val md_theme_dark_tertiaryContainer = Color(0xFF00497E)
val md_theme_dark_onTertiaryContainer = Color(0xFFD2E4FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF001F25)
val md_theme_dark_onBackground = Color(0xFFA6EEFF)
val md_theme_dark_surface = Color(0xFF001F25)
val md_theme_dark_onSurface = Color(0xFFA6EEFF)
val md_theme_dark_surfaceVariant = Color(0xFF4C4639)
val md_theme_dark_onSurfaceVariant = Color(0xFFCFC6B4)
val md_theme_dark_outline = Color(0xFF989080)
val md_theme_dark_inverseOnSurface = Color(0xFF001F25)
val md_theme_dark_inverseSurface = Color(0xFFA6EEFF)
val md_theme_dark_inversePrimary = Color(0xFF735C00)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFE9C348)
val md_theme_dark_outlineVariant = Color(0xFF4C4639)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFFFDEDC7)
